// Copyright 2025 fsyyft-ai
//
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package chat

import (
	appconf "github.com/fsyyft-ai/eino-wizard/internal/conf"
	applog "github.com/fsyyft-ai/eino-wizard/internal/log"
	apptask "github.com/fsyyft-ai/eino-wizard/internal/task"
	appquickstart "github.com/fsyyft-ai/eino-wizard/internal/task/quickstart"
)

// Injectors from wire.go:

func wireTask(cfg *appconf.Config) (apptask.QuickStart, func(), error) {
	logger, cleanup, err := applog.NewLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	chat, err := appquickstart.NewChat(logger, cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	quickStart, err := apptask.NewQuickStart(logger, cfg, chat)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return quickStart, func() {
		cleanup()
	}, nil
}
