// Copyright 2025 fsyyft-ai
//
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package chat

import (
	appconf "github.com/fsyyft-ai/eino-wizard/internal/conf"
	applog "github.com/fsyyft-ai/eino-wizard/internal/log"
	apptask "github.com/fsyyft-ai/eino-wizard/internal/task"
)

// Injectors from wire.go:

func wireTask(cfg *appconf.Config) (apptask.QuickStartChat, func(), error) {
	logger, cleanup, err := applog.NewLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	quickStartChat, err := apptask.NewQuickStartChat(logger, cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return quickStartChat, func() {
		cleanup()
	}, nil
}
